name: images

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: auth
        uses: docker/build-push-action@v3
        with:
          context: auth
          push: true
          tags: ghcr.io/breuerfelix/connact/auth:latest
      - name: users
        uses: docker/build-push-action@v3
        with:
          context: users
          push: true
          tags: ghcr.io/breuerfelix/connact/users:latest
