name: images

on:
  push:
    branches: ['**']
    tags: ['v*.*.*']

jobs:
  images:
    strategy:
      matrix:
        image: [auth, user, radicale, sync, search, relation]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        id: meta
        name: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: set up buildx
        uses: docker/setup-buildx-action@v2
      -
        name: login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

